services:
  mysql:
    restart: always
    build:
      context: ./mysql
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_USER=default
      - MYSQL_PASSWORD=my_secret
      - MYSQL_ROOT_PASSWORD=95279527
    volumes:
      #- VOLUMES_PATH_HOST/mysql:/var/lib/mysql
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql:
    driver: local

networks:
  ssdocker:
    driver: bridge
